### ISSUE TITLE
Remove extra attributes

### ISSUE THREAD

**Issue by rgant** [BlairAllegroTech/js-data-jsonapi#16]
I've noticed that the data.attributes sent to the server contains an extra key called "$_JSONAPIMETA_".

There is a similar issue with `$$hashKey` which is added by ng-repeat from Angular. js-data resolved a bug with this key in https://github.com/js-data/js-data-angular/issues/208

I added checks for these two values here:  https://github.com/BlairAllegroTech/js-data-jsonapi/blob/js-data-jsonapi/src/JsonApiSerializer.ts#L861

```
if (prop === options.idAttribute || prop === JSONAPI_META || prop === '$$hashKey') {
    continue;
}
```

It might be better to keep track of which attributes came from the server and which didn't, but then you get into issues with

**Comment by BlairAllegroTech** [comment]
Thanks, i was of the understanding that js-data ignored properties starting with '$'  but this may just be for change tracking.

I'll strip this property off of any outgoing requests in the serializer.

**Comment by rgant** [comment]
Interesting, let me check the spec, maybe I did the API wrong.

Hmmm, in the upcoming version (v1.1) I see that the spec will ignore "@-members":
http://jsonapi.org/format/upcoming/#document-member-names-at-members

Problem with that is that so many of the JS libraries use $ for internal stuff. Maybe that will change before the spec gets released.

-_Rob

**Comment by BlairAllegroTech** [comment]
No i thought js-data would ignore all attributes starting with $. I had assumed it would not send them..
But i think this may just be for change tracking
