### ISSUE TITLE
Availability of the library through bower.

### ISSUE THREAD

**Issue by alexKanda** [BlairAllegroTech/js-data-jsonapi#3]
Could you check availability of the library through bower ? At the moment it can't be found via bower ? Thx.

**Comment by BlairAllegroTech** [comment]
No to date i have not published npm or bower packages. I can do though...

**Comment by alexKanda** [comment]
We would like to use your adapter and it would be very good if you could publish a version for bower - it would be very convenient. "I can do though..." - Do You have this in future plans ? Thx.

**Comment by BlairAllegroTech** [comment]
Yes I will look into this asap.

Sent from Yahoo Mail on Android 

  On Tue, 29 Mar, 2016 at 23:56, alexKandanotifications@github.com wrote:  
We would like to use your adapter and it would be very good if you could publish a version for bower - it would be very convenient. Do You have this in future plans ? Thx.

**Comment by BlairAllegroTech** [comment]
@alexKanda if its any help i just published an npm package. js-data-jsonapi

**Comment by kawabanga01** [comment]
Hi @BlairAllegroTech. Your module very helps me in my work. Could you add this lib in bower ? Npm repository not good solution for me :(

**Comment by BlairAllegroTech** [comment]
Published today
