### ISSUE TITLE
Missing dist directory

### ISSUE THREAD

**Issue by utf4** [BlairAllegroTech/js-data-jsonapi#35]
I have installed js-data-jsonapi and its depenencies via bower to my project but I am unsure which file I have to add for js-data-jsonapi into my project's <scripts>. Even dist directory missing. Do I have to build it byself before using?

**Comment by BlairAllegroTech** [comment]
@furqanaziz Try this, sorry haven't had much experience with bower....
Let me know if you are happy with the changes then we can close this issue

Appreciate your feedback

**Comment by utf4** [comment]
Yes this is working perfectly fine now. Thanks a lot. You can close it.
