### ISSUE TITLE
NPM Package Published

### ISSUE THREAD

**Issue by BlairAllegroTech** [BlairAllegroTech/js-data-jsonapi#4]
Any feedback appreciated

**Comment by BlairAllegroTech** [comment]
No feedback so i will assume there are no problems with this package

**Comment by NullVoxPopuli** [comment]
how do I import this?

in an angular project I tired

``` ts
import { DSJsonApiAdapter } from 'js-data-jsonapi';
```

and I got the error: 

```
Cannot find module 'js-data-jsonapi'.
```

**Comment by BlairAllegroTech** [comment]
@NullVoxPopuli I think if you are running in a browser you just need to reference the javascript file using an html script tag.

You can not import modules natively in a browser..
https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import

**Comment by NullVoxPopuli** [comment]
well, I'm using typescript, and angular-cli with the latest angular-2, so I should be able to. It's not pure browser -- it's pre-browser / pre-transpiled js.
