### ISSUE TITLE
The saved/installed package doesn't have d.ts files?

### ISSUE THREAD

**Issue by NullVoxPopuli** [BlairAllegroTech/js-data-jsonapi#6]
under dist is just min.map, min, and the uncompressed js

**Comment by NullVoxPopuli** [comment]
![image](https://cloud.githubusercontent.com/assets/199018/15827317/fd81a49a-2bd8-11e6-8572-9a5cf4798d37.png)

**Comment by BlairAllegroTech** [comment]
No i didn't not publish any specific typings as you should interact with this adapter in the same way as any other js-data adapter. The adapter implements the js-data interface `JSData.IDSAdapter` and its type definitions is are available from  [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped)

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/js-data-http
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/js-data

**Comment by NullVoxPopuli** [comment]
I think maybe it's an incompatibility with js-data 3, then. cause I can use js-data-http just fine

**Comment by BlairAllegroTech** [comment]
Good point this is a js-data V2 adapter. 
I need to start looking at V3 and create a V3 branch.
Created Task: #7

The NPM package does define the dependency on js-data as being < 3.
